const CourseData = {
    Sticksjo : {
        '1': {
            id: 1,
            name: "Hål 1",
            lenght: 121,
            altLenght: null,
            par: 3,
            metersLeft: 50,
            blackSign: "Mot hål 2/tee 2",
            graySign: null,
            ob: "OB linje till höger om banan",
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole1.png",
            src: require('../Images/hole1.png')
        },
        '2': {
            id: 2,
            name: "Hål 2",
            lenght: 97,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 3/tee 3",
            graySign: "Mot främre tee hål 3/tee 3",
            ob: null,
            well: "Brunn",
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole2.png",
            src: require("../Images/hole2.png")
        },
        '3': {
            id: 3,
            name: "Hål 3",
            lenght: 178,
            altLenght: 150,
            par: 4,
            metersLeft: 70,
            blackSign: "Mot hål 4/tee 4",
            graySign: null,
            ob: null,
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole3.png",
            src: require("../Images/hole3.png")
        },
        '4': {
            id: 4,
            name: "Hål 4",
            lenght: 71,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 5/tee 5",
            graySign: null,
            ob: "Missar du ön på första kastet gå till dropzone och gör ditt tredje kast. Därefter gäller vanliga OB regler",
            well: null,
            dropZone: "Drop zone",
            mando: null,
            stone: null,
            image: "../Images/hole4.png",
            src: require("../Images/hole4.png")
        },
        '5': {
            id: 5,
            name: "Hål 5",
            lenght: 128,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 6/tee 6",
            graySign: null,
            ob: null,
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole5.png",
            src: require("../Images/hole5.png")
        },
        '6': {
            id: 6,
            name: "Hål 6",
            lenght: 105,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 7/tee 7",
            graySign: null,
            ob: null,
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole6.png",
            src: require("../Images/hole6.png")
        },  
        '7': {
            id: 7,
            name: "Hål 7",
            lenght: 90,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 8/tee 8",
            graySign: null,
            ob: null,
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole7.png",
            src: require("../Images/hole7.png")
        },
        '8': {
            id: 8,
            name: "Hål 8",
            lenght: 132,
            altLenght: null,
            par: 4,
            metersLeft: 70,
            blackSign: "Mot hål 9/tee 9",
            graySign: null,
            ob: "Re-throw utan plikt om du missar första mandoträdet. Vid miss av andra mandot kastas nästa disc vid dropzone med plikt.",
            well: null,
            dropZone: "Drop zone",
            mando: "Mandoträd",
            stone: null,
            image: "../Images/hole8.png",
            src: require("../Images/hole8.png")
        },
        '9': {
            id: 9,
            name: "Hål 9",
            lenght: 81,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 10/tee 10",
            graySign: null,
            ob: null,
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole9.png",
            src: require("../Images/hole9.png")
        },
        '10': {
            id: 10,
            name: "Hål 10",
            lenght: 90,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 11/tee 11",
            graySign: null,
            ob: null,
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole10.png",
            src: require("../Images/hole10.png")
        },
        '11': {
            id: 11,
            name: "Hål 11",
            lenght: 90,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 12/tee 12",
            graySign: null,
            ob: "Kast från tee i vatten = dropzone. Därefter gäller vanliga OB regler. PS. vattenslangen markerar ob-linje.",
            well: null,
            dropZone: "Drop zone",
            mando: null,
            stone: "Sten",
            image: "../Images/hole11.png",
            src: require("../Images/hole11.png")
        },
        '12': {
            id: 12,
            name: "Hål 12",
            lenght: 107,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 13/tee 13",
            graySign: null,
            ob: null,
            well: null,
            dropZone: null,
            mando: null,
            stone: "Sten",
            image: "../Images/hole12.png",
            src: require("../Images/hole12.png")
        },
        '13': {
            id: 13,
            name: "Hål 13",
            lenght: null,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 14/tee 14",
            graySign: null,
            ob: null,
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole13.png",
            src: require("../Images/hole13.png")
        },
        '14': {
            id: 14,
            name: "Hål 14",
            lenght: 79,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 15/tee 15",
            graySign: null,
            ob: "OB mot grusvägen.",
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole14.png",
            src: require("../Images/hole14.png")
        },
        '15': {
            id: 15,
            name: "Hål 15",
            lenght: 109,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 16/tee 16",
            graySign: null,
            ob: "OB längs med grusvägen. Vanliga OB regler gäller.",
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole15.png",
            src: require("../Images/hole15.png")
        },
        '16': {
            id: 16,
            name: "Hål 16",
            lenght: 150,
            altLenght: null,
            par: 4,
            metersLeft: null,
            blackSign: "Mot hål 17/tee 17",
            graySign: null,
            ob: null,
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole16.png",
            src: require("../Images/hole16.png")
        },
        '17': {
            id: 17,
            name: "Hål 17",
            lenght: 199,
            altLenght: null,
            par: 5,
            metersLeft: 100,
            blackSign: "Mot hål 18/tee 18",
            graySign: null,
            ob: null,
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole17.png",
            src: require("../Images/hole17.png")
        },
        '18': {
            id: 18,
            name: "Hål 18",
            lenght: 75,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 1/tee 1",
            graySign: null,
            ob: "Vattnet till vänster är OB. Hundbad till vänster, var försiktig.",
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole18.png",
            src: require("../Images/hole18.png")
        }
    },
    Fagervik : {
        '1': {
            id: 1,
            name: "Hål 1",
            lenght: 121,
            altLenght: null,
            par: 3,
            metersLeft: 50,
            blackSign: "Mot hål 2/tee 2",
            graySign: null,
            ob: "OB linje till höger om banan",
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole1.png",
            src: require('../Images/hole1.png')
        },
        '2': {
            id: 2,
            name: "Hål 2",
            lenght: 97,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 3/tee 3",
            graySign: "Mot främre tee hål 3/tee 3",
            ob: null,
            well: "Brunn",
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole2.png",
            src: require("../Images/hole2.png")
        },
        '3': {
            id: 3,
            name: "Hål 3",
            lenght: 178,
            altLenght: 150,
            par: 4,
            metersLeft: 70,
            blackSign: "Mot hål 4/tee 4",
            graySign: null,
            ob: null,
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole3.png",
            src: require("../Images/hole3.png")
        },
        '4': {
            id: 4,
            name: "Hål 4",
            lenght: 71,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 5/tee 5",
            graySign: null,
            ob: "Missar du ön på första kastet gå till dropzone och gör ditt tredje kast. Därefter gäller vanliga OB regler",
            well: null,
            dropZone: "Drop zone",
            mando: null,
            stone: null,
            image: "../Images/hole4.png",
            src: require("../Images/hole4.png")
        },
        '5': {
            id: 5,
            name: "Hål 5",
            lenght: 128,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 6/tee 6",
            graySign: null,
            ob: null,
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole5.png",
            src: require("../Images/hole5.png")
        },
        '6': {
            id: 6,
            name: "Hål 6",
            lenght: 105,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 7/tee 7",
            graySign: null,
            ob: null,
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole6.png",
            src: require("../Images/hole6.png")
        },  
        '7': {
            id: 7,
            name: "Hål 7",
            lenght: 90,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 8/tee 8",
            graySign: null,
            ob: null,
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole7.png",
            src: require("../Images/hole7.png")
        },
        '8': {
            id: 8,
            name: "Hål 8",
            lenght: 132,
            altLenght: null,
            par: 4,
            metersLeft: 70,
            blackSign: "Mot hål 9/tee 9",
            graySign: null,
            ob: "Re-throw utan plikt om du missar första mandoträdet. Vid miss av andra mandot kastas nästa disc vid dropzone med plikt.",
            well: null,
            dropZone: "Drop zone",
            mando: "Mandoträd",
            stone: null,
            image: "../Images/hole8.png",
            src: require("../Images/hole8.png")
        },
        '9': {
            id: 9,
            name: "Hål 9",
            lenght: 81,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 10/tee 10",
            graySign: null,
            ob: null,
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole9.png",
            src: require("../Images/hole9.png")
        },
        '10': {
            id: 10,
            name: "Hål 10",
            lenght: 90,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 11/tee 11",
            graySign: null,
            ob: null,
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole10.png",
            src: require("../Images/hole10.png")
        },
        '11': {
            id: 11,
            name: "Hål 11",
            lenght: 90,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 12/tee 12",
            graySign: null,
            ob: "Kast från tee i vatten = dropzone. Därefter gäller vanliga OB regler. PS. vattenslangen markerar ob-linje.",
            well: null,
            dropZone: "Drop zone",
            mando: null,
            stone: "Sten",
            image: "../Images/hole11.png",
            src: require("../Images/hole11.png")
        },
        '12': {
            id: 12,
            name: "Hål 12",
            lenght: 107,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 13/tee 13",
            graySign: null,
            ob: null,
            well: null,
            dropZone: null,
            mando: null,
            stone: "Sten",
            image: "../Images/hole12.png",
            src: require("../Images/hole12.png")
        },
        '13': {
            id: 13,
            name: "Hål 13",
            lenght: null,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 14/tee 14",
            graySign: null,
            ob: null,
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole13.png",
            src: require("../Images/hole13.png")
        },
        '14': {
            id: 14,
            name: "Hål 14",
            lenght: 79,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 15/tee 15",
            graySign: null,
            ob: "OB mot grusvägen.",
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole14.png",
            src: require("../Images/hole14.png")
        },
        '15': {
            id: 15,
            name: "Hål 15",
            lenght: 109,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 16/tee 16",
            graySign: null,
            ob: "OB längs med grusvägen. Vanliga OB regler gäller.",
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole15.png",
            src: require("../Images/hole15.png")
        },
        '16': {
            id: 16,
            name: "Hål 16",
            lenght: 150,
            altLenght: null,
            par: 4,
            metersLeft: null,
            blackSign: "Mot hål 17/tee 17",
            graySign: null,
            ob: null,
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole16.png",
            src: require("../Images/hole16.png")
        },
        '17': {
            id: 17,
            name: "Hål 17",
            lenght: 199,
            altLenght: null,
            par: 5,
            metersLeft: 100,
            blackSign: "Mot hål 18/tee 18",
            graySign: null,
            ob: null,
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole17.png",
            src: require("../Images/hole17.png")
        },
        '18': {
            id: 18,
            name: "Hål 18",
            lenght: 75,
            altLenght: null,
            par: 3,
            metersLeft: null,
            blackSign: "Mot hål 1/tee 1",
            graySign: null,
            ob: "Vattnet till vänster är OB. Hundbad till vänster, var försiktig.",
            well: null,
            dropZone: null,
            mando: null,
            stone: null,
            image: "../Images/hole18.png",
            src: require("../Images/hole18.png")
        }
    },
};

export default CourseData